version: "3"

services:
  app:
    image: node:10
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - mongo
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    command: npm run dev

  mongo:
    container_name: mongo
    image: mongo
    expose:
      - 27017
    volumes:
      - ./data/db:/data/db
